apps:
  qq:
    enabled: false
    startup:
      enable_listener: true
  diary:
    enabled: true
    startup: {}
  alarm:
    enabled: true
    startup: {}
  weather:
    enabled: false
    startup: {}
  clock:
    enabled: false
    startup: {}
